# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

jobs:
- job: validation

  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    imageName: 'terraform-azurerm-postgresql:$(build.buildId)'

  steps:
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'

  - script: docker run -e "ARM_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID" -e "ARM_CLIENT_ID=$AZURE_CLIENT_ID" -e "ARM_CLIENT_SECRET=$AZURE_CLIENT_SECRET" -e "ARM_TENANT_ID=$AZURE_TENANT_ID" -e "ARM_TEST_LOCATION=WestUS2" -e "ARM_TEST_LOCATION_ALT=EastUS" --rm $(imageName) bash -c "./test.sh validate"
    displayName: 'docker run'

- job: full

  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    imageName: 'terraform-azurerm-postgresql:$(build.buildId)'

  trigger: master

  steps:
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'

  - script: docker run -e "ARM_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID" -e "ARM_CLIENT_ID=$AZURE_CLIENT_ID" -e "ARM_CLIENT_SECRET=$AZURE_CLIENT_SECRET" -e "ARM_TENANT_ID=$AZURE_TENANT_ID" -e "ARM_TEST_LOCATION=WestUS2" -e "ARM_TEST_LOCATION_ALT=EastUS" --rm $(imageName) bash -c "./test.sh full"
    displayName: 'docker run'
